# Info website
title: "BranJournal"
description: "Catatan perjalanan, tulisan, dan cerita sederhana."
author: "Haidar Ahmad Zabran Aliyuddin"

# Link utama (URL website)
url: "https://zaburrr.github.io"
baseurl: "/branjournal"   # nama repo kamu

# Setting build
markdown: kramdown
permalink: /:categories/:title/

# Folder default Jekyll
layouts_dir: _layouts
includes_dir: _includes
collections:
  posts:
    output: true

# Plugin bawaan GitHub Pages (aman digunakan)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
